global:
  name: consul
  datacenter: dc1
  openshift:
    enabled: true
server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
client:
  enabled: true
  grpc: true
ui:
  enabled: true
connectInject:
  enabled: true
  default: true
  transparentProxy:
    defaultEnabled: true
controller:
  enabled: true

